version: '3.8'
services:
  web:
    image: nginx

    restart: always
    ports:
          - 8000:80
    environment:
      - apiserver=apiserver
      - TZ=Asia/Tokyo
    volumes:
      - ./video:/var/www/html/video
      - ./nginx/nginx.conf:/etc/nginx/conf.d/mysite.template
    command: /bin/bash -c  "envsubst '$$apiserver' < /etc/nginx/conf.d/mysite.template > /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"
    logging:
      driver: "json-file"
      options:
        max-size: "3m"
        max-file: "1"
  
  apiserver:
    build:
      context: .
      dockerfile: ./docker/nvenc-api/Dockerfile
    
    environment:
      - TZ=Asia/Tokyo
    volumes:
      - ./:/videoapi

    devices:
      - /dev/dri:/dev/dri
      - /dev/dri/renderD128:/dev/dri/renderD128
      - /dev/dri/card0:/dev/dri/card0
      
    command: /bin/sh -c  "cd videoapi &&./start.sh "
    logging:
     driver: "json-file"
     options:
       max-size: "1m"
       max-file: "1"
    deploy:
      resources:
        reservations:
          devices:
          - capabilities: [utility, compute, video]