version: '3.8'
services:
  web:
    image: nginx

    restart: always
    ports:
          - 8000:80
    environment:
      - apiserver=apiserver
      - TZ=Asia/Tokyo
      - BASIC_USER=user
      - BASIC_PASS=pass
    volumes:
      - videodata:/var/www/html/video
      - filedata:/var/www/html/file
      - $PWD/nginx/templates:/etc/nginx/templates
      - $PWD/nginx/basic.sh:/docker-entrypoint.d/basic.sh
    logging:
      driver: "json-file"
      options:
        max-size: "3m"
        max-file: "1"
  
  apiserver:
    build:
      context: .
      dockerfile: ./docker/general-api/Dockerfile
    restart: always
    environment:
      - TZ=Asia/Tokyo
    volumes:
      - videodata:/videoapi/video
      - filedata:/videoapi/file
      - $PWD/:/videoapi

    devices:
      - /dev/dri:/dev/dri
      - /dev/dri/renderD128:/dev/dri/renderD128
      - /dev/dri/card0:/dev/dri/card0
      
    command: /bin/sh -c  "cd videoapi &&./start.sh "
    logging:
     driver: "json-file"
     options:
       max-size: "1m"
       max-file: "1"
volumes:
  videodata:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '$PWD/video'
  filedata:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '$PWD/file'